[build-system]
requires = [
    "setuptools",
    "numpy",
    "taurex",
    "matplotlib",
    "tqdm",
    "pandas",
    "gdown",
    "pyarrow",
    "joblib",
    "astropy"
]
build-backend = "setuptools.build_meta"
